const fs = require('fs');

// Keys we expect Vercel (or any CI) to provide as env vars
const keys = [
  'FIREBASE_API_KEY',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET',
  'FIREBASE_MESSAGING_SENDER_ID',
  'FIREBASE_APP_ID',
  'ADMIN_PIN'
];

const missing = keys.filter(k => !process.env[k]);

if (missing.length) {
  console.warn('build-config: Missing environment variables:', missing.join(', '));
  // Still produce a file with what we have to avoid runtime crashes, but flagged
}

const env = keys.reduce((acc, k) => {
  acc[k] = process.env[k] || '';
  return acc;
}, {});

const content = `// Auto-generated by build-config.js - DO NOT EDIT\nwindow.process = { env: ${JSON.stringify(env, null, 2)} };\n`;

fs.writeFileSync('config.js', content, 'utf8');
console.log('build-config: config.js generated');
